<?php

include_once('my_site.features.inc');

/**
 * Implements hook_page_alter().
 *
 * Fix occurrence of both toolbar and admin_menu. Remove toolbar if the user can access admin_menu.
 */
function my_site_page_alter(&$page) {
  // Hide Toolbar for those who can access the Admin Menu.
  if (user_access('access administration menu') && !empty($page['page_top']['toolbar'])) {
    $page['page_top']['toolbar']['#access'] = FALSE;
  }
}

/**
 * Implements hook_views_api().
 */
function my_site_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'my_site'),
  );
}

