# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  - 5.4

mysql:
 database: drupal
 username: root
 encoding: utf8

install:

 - sudo apt-get update > /dev/null
 - "mysql -e 'create database drupal;'"

 # Install latest Drush 6.
 - export PATH="$HOME/.composer/vendor/bin:$PATH"
 - composer global require --no-interaction --prefer-source drush/drush:6.*
 - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
 - drush cc drush

 # Build Behat dependencies
 - cd ./tests/behat
 - composer install --no-interaction --prefer-source
 - cd ../../../

 # Setting Behat environment
 - DISTRO=`echo $TRAVIS_BUILD_DIR | sed -e "s/\/[^\/]*$//"`
 - export BEHAT_PARAMS="extensions[Drupal\\DrupalExtension\\Extension][drupal][drupal_root]=$DISTRO/drupal"

 # Build Codebase
 - mkdir private_files
 - mkdir profiles
 - mv my profiles/
 - mkdir drupal
 - mv profiles drupal/

 # Build the current branch
 - cd drupal
 - drush make --yes profiles/my/drupal-org-core.make --prepare-install
 - drush make --yes profiles/my/my.make --no-core --contrib-destination=profiles/my
 - cd ../

 # Setup files
 - sudo chmod -R 777 drupal/sites/all

 # Setup display for Selenium
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 5

 # Get Selenium
 - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.1.jar
 - java -jar selenium-server-standalone-2.42.1.jar > /dev/null 2>&1 &
 - until netstat -an 2>/dev/null | grep '4444.*LISTEN'; do true; done

 # Disable sendmail
 - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
 # Do the site install
 - cd drupal
 - drush site-install my --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="MY" --yes

 # Enable migrate and test migrate examples
 - drush en migrate,my_migrate_example -y
 - drush mreg
 - drush mi --group=my_example

 # Start server
 - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
 - until netstat -an 2>/dev/null | grep '8888.*LISTEN'; do true; done
 - cd profiles/my/tests/behat

script:

 # Run Behat tests
 - ./bin/behat --config behat.travis.yml

notifications:
 # Our MY Flowdock chat
 flowdock: 5c81bb34f6ca9c86da0d32d92596a3db
